### ISSUE TITLE
Create a new release to update to newer canvas for Node 18 support

### ISSUE THREAD

**Issue by sampsakuronen** [k-yle/pdf-to-img#186]
`canvas` has recently solved its compatibility with Node 18 (please see https://github.com/Automattic/node-canvas/issues/2025). By updating to `>2.10.2` of `canvas` this package could also be compatible with Node 18 and following that, the downstream projects could update to Node 18.

The update has already been merged to `main` in https://github.com/k-yle/pdf-to-img/commit/a626d1f7a88150ecbbcbdfe4e55d88d0413400ec but no new release has been done yet.

**Comment by k-yle** [comment]
hey, thanks for the heads up. I've released v2.0.0 which has node v18 and v19 support

**Comment by sampsakuronen** [comment]
Thank you!
