### ISSUE TITLE
No native dependencies is not true

### ISSUE THREAD

**Issue by jakeleventhal** [k-yle/pdf-to-img#212]
The README mentions the package has no native dependencies, yet on macOS, `brew install mango && brew install cairo` is needed

**Comment by whyboris** [comment]
Seems to have worked on _Windows_ 10 without needing anything extra 🤔

**Comment by k-yle** [comment]
hi, yeah I agree the current phrasing is a bit misleading, as @whyboris noted, they key point is that you don't need to compile any native code in most cases (with the exception of rare OS/NodeJS combinations which don't have pre-built binaries)

I'm open to rewording the strapline, any suggestions?

**Comment by bkniffler** [comment]
Just remove the claim or add note that you use node canvas which might need compilation. I for example am not able to use pdf-to-img because node canvas compilation fails for my m3 mac.
