### ISSUE TITLE
Can I convert to JPG and save to filesystem in Node?

### ISSUE THREAD

**Issue by Konglomneshued** [k-yle/pdf-to-img#213]
It's not really clear how to use the document returned from the pdf function call.  It's not mentioned what type of image is created either.

**Comment by ve3** [comment]
I agree to see simple example **without [jest-image-snapshot](https://npm.im/jest-image-snapshot)**.

For example
```
for await (const page of await pdf("example.pdf")) {
    // what to do with `page`?
}
```
