### ISSUE TITLE
Add option to select pages that should be converted

### ISSUE THREAD

**Issue by sbrglnd** [k-yle/pdf-to-img#237]
High quality conversions of PDFs with a high number of pages takes a lot of time.
Adding an option to select which pages of the PDF to convert would optimize scenarios in which you know which pages you want to convert.

Apart from that the package work wonders!

**Comment by k-yle** [comment]
Hi, this is now possible in the latest version. I've update the example on the readme:

```js
  const document = await pdf("example.pdf");

  // current approach:
  for await (const page of document) {
    
  }

  // or you can also read a specific page number:
  const page = await document.getPage(12)
```

**Comment by sbrglnd** [comment]
Works great, thank you ✌️
