### ISSUE TITLE
polyfill causing an issue with Next.JS 14

### ISSUE THREAD

**Issue by AChangXD** [k-yle/pdf-to-img#239]
I'm using this library in Next.JS 14's API route handler, and the polyfill is causing an issue where it would completely crash the application with the error:

`TypeError: Cannot destructure property 'protocol' of 'window.location' as it is undefined.
    at getLocationOrigin`

I can comment out the polyfill and things will work. Is there a way to automatically detect if the package is being used in NextJS and do not perform the polyfill?

**Comment by BlakeBrown** [comment]
Getting this issue as well
