### ISSUE TITLE
Specify tighter version on pdfjs-dist in package.json

### ISSUE THREAD

**Issue by mattddean** [k-yle/pdf-to-img#65]
Thought the package-lock.json file contains the correct version, the version pattern for pdfjs-dist allows for a version of pdfjs-dist that seems to rename the `es5` directory to `legacy`. Thus, an error is thrown when this package is used as a dependency of another project without that dependent project explicitly setting its pdfjs-dist version to `2.7.570`

Please update:

```json
"pdfjs-dist": "^2.7.570"
```

to 

```json
"pdfjs-dist": "~2.7.570"
```

**Comment by k-yle** [comment]
thanks for the report, I've fixed this in #58. As of `v1.1.1` we pin dependencies to prevent this from happening again
